#!/usr/bin/env python3

# Part of Ariadne Shell Handler (a fork of Penelope, GPL-3.0-or-later). See LICENSE.

URLS = {
	'python_linux_x86_64_glibc':'https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.13.14+20260610-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz',
	'python_linux_x86_64_musl':'https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.13.14+20260610-x86_64-unknown-linux-musl-install_only_stripped.tar.gz',
	'python_linux_aarch64_glibc':'https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.13.14+20260610-aarch64-unknown-linux-gnu-install_only_stripped.tar.gz',
	'python_linux_aarch64_musl':'https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.13.14+20260610-aarch64-unknown-linux-musl-install_only_stripped.tar.gz',
	'python_macos_x86_64':'https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.13.14+20260610-x86_64-apple-darwin-install_only_stripped.tar.gz',
	'python_macos_aarch64':'https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.13.14+20260610-aarch64-apple-darwin-install_only_stripped.tar.gz',
	'linpeas':	"https://github.com/peass-ng/PEASS-ng/releases/latest/download/linpeas.sh",
	'winpeas_bat':	"https://github.com/peass-ng/PEASS-ng/releases/latest/download/winPEAS.bat",
	'winpeas_any':	"https://github.com/peass-ng/PEASS-ng/releases/latest/download/winPEASany.exe",
	'ncat':		"https://raw.githubusercontent.com/andrew-d/static-binaries/master/binaries/linux/x86_64/ncat",
	'lse':		"https://raw.githubusercontent.com/diego-treitos/linux-smart-enumeration/master/lse.sh",
	'powerup':	"https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/refs/heads/master/Privesc/PowerUp.ps1",
	'deepce':	"https://raw.githubusercontent.com/stealthcopter/deepce/refs/heads/main/deepce.sh",
	'privesccheck':	"https://github.com/itm4n/PrivescCheck/releases/latest/download/PrivescCheck.ps1",
	'les':		"https://raw.githubusercontent.com/The-Z-Labs/linux-exploit-suggester/refs/heads/master/linux-exploit-suggester.sh",
	'linenum':		"https://raw.githubusercontent.com/rebootuser/LinEnum/refs/heads/master/LinEnum.sh",
	'amicontained':		"https://github.com/genuinetools/amicontained/releases/download/v0.4.0/amicontained-linux-amd64",
	'cdk':		"https://github.com/cdk-team/CDK/releases/latest/download/CDK_linux_amd64",
	'ngrok_linux':	"https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz",
	'uac_linux':	"https://github.com/tclahr/uac/releases/download/v3.2.0/uac-3.2.0.tar.gz",
	'linux_procmemdump':	"https://raw.githubusercontent.com/tclahr/uac/refs/heads/main/bin/linux/linux_procmemdump.sh",
	'traitor_386':		"https://github.com/liamg/traitor/releases/latest/download/traitor-386",
	'traitor_amd64':	"https://github.com/liamg/traitor/releases/latest/download/traitor-amd64",
	'traitor_arm64':	"https://github.com/liamg/traitor/releases/latest/download/traitor-arm64",
	'pspy32':	"https://github.com/DominicBreuker/pspy/releases/latest/download/pspy32",
	'pspy64':	"https://github.com/DominicBreuker/pspy/releases/latest/download/pspy64",
	'panix':	"https://github.com/Aegrah/PANIX/releases/latest/download/panix.sh",
	'chisel_386':	"https://github.com/jpillora/chisel/releases/download/v1.11.3/chisel_1.11.3_linux_386.gz",
	'chisel_amd64':	"https://github.com/jpillora/chisel/releases/download/v1.11.3/chisel_1.11.3_linux_amd64.gz",
	'chisel_arm64':	"https://github.com/jpillora/chisel/releases/download/v1.11.3/chisel_1.11.3_linux_arm64.gz",
	'chisel_win386':	"https://github.com/jpillora/chisel/releases/download/v1.11.3/chisel_1.11.3_windows_386.zip",
	'chisel_winamd64':	"https://github.com/jpillora/chisel/releases/download/v1.11.3/chisel_1.11.3_windows_amd64.zip",
	'ligolo_amd64':		"https://github.com/nicocha30/ligolo-ng/releases/download/v0.8.3/ligolo-ng_agent_0.8.3_linux_amd64.tar.gz",
	'ligolo_arm64':		"https://github.com/nicocha30/ligolo-ng/releases/download/v0.8.3/ligolo-ng_agent_0.8.3_linux_arm64.tar.gz",
	'ligolo_win64':		"https://github.com/nicocha30/ligolo-ng/releases/download/v0.8.3/ligolo-ng_agent_0.8.3_windows_amd64.zip",
	'snaffler':		"https://github.com/SnaffCon/Snaffler/releases/latest/download/Snaffler.exe",
	'lazagne':		"https://github.com/AlessandroZ/LaZagne/releases/latest/download/LaZagne.exe",
	'mimikatz':		"https://github.com/gentilkiwi/mimikatz/releases/latest/download/mimikatz_trunk.zip",
	'sharphound':		"https://github.com/SpecterOps/SharpHound/releases/download/v2.13.0/SharpHound_v2.13.0_windows_x86.zip",
	'powerview':		"https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/refs/heads/master/Recon/PowerView.ps1",
	'sharpweb':		"https://github.com/djhohnstein/SharpWeb/releases/download/v1.2/SharpWeb.exe",
	'ghostpack':		"https://codeload.github.com/r3motecontrol/Ghostpack-CompiledBinaries/zip/20a5f0a81456358b2bdc9846774949a7fb25acd8",
	'adpeas':		"https://raw.githubusercontent.com/61106960/adPEAS/main/adPEAS.ps1",
	'conptyshell':		"https://raw.githubusercontent.com/antonioCoco/ConPtyShell/refs/heads/master/Invoke-ConPtyShell.ps1",
	'godpotato':		"https://github.com/BeichenDream/GodPotato/releases/download/V1.20/GodPotato-NET4.exe",
	'sigmapotato':		"https://github.com/tylerdotrar/SigmaPotato/releases/download/v1.2.6/SigmaPotato.exe",
	'printspoofer64':	"https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer64.exe",
	'printspoofer32':	"https://github.com/itm4n/PrintSpoofer/releases/download/v1.0/PrintSpoofer32.exe",
	'dirtyfrag':		"https://raw.githubusercontent.com/V4bel/dirtyfrag/refs/heads/master/exp.c",
	'dirtypipe_zip':	"https://github.com/AlexisAhmed/CVE-2022-0847-DirtyPipe-Exploits/archive/refs/heads/main.zip",
	'fullpowers':		"https://github.com/itm4n/FullPowers/releases/download/v0.1/FullPowers.exe",
	'enablealltokenprivs':	"https://raw.githubusercontent.com/fashionproof/EnableAllTokenPrivs/3f108e80d6c460a2e554b18e9d3391d976b93ed2/EnableAllTokenPrivs.ps1",
	'sharpup':		"https://raw.githubusercontent.com/r3motecontrol/Ghostpack-CompiledBinaries/master/SharpUp.exe",
	'sharpdpapi':		"https://raw.githubusercontent.com/r3motecontrol/Ghostpack-CompiledBinaries/master/SharpDPAPI.exe",
	'peirates':		"https://github.com/inguardians/peirates/releases/latest/download/peirates-linux-amd64.tar.xz",
	'kubeletctl':		"https://github.com/cyberark/kubeletctl/releases/latest/download/kubeletctl_linux_amd64",
}


PYTHON_STANDALONE_BINARIES = {
	('Linux', 'x86_64', 'glibc'): 'python_linux_x86_64_glibc',
	('Linux', 'x86_64', 'musl'): 'python_linux_x86_64_musl',
	('Linux', 'aarch64', 'glibc'): 'python_linux_aarch64_glibc',
	('Linux', 'aarch64', 'musl'): 'python_linux_aarch64_musl',

	('Darwin', 'x86_64'): 'python_macos_x86_64',
	('Darwin', 'arm64'): 'python_macos_aarch64',
}
